### ISSUE TITLE
i got a bad error

### ISSUE THREAD

**Issue by bluethefoxyt** [developerCodex/musicbot#24]
TypeError: Cannot read property 'length' of undefined

**Comment by ZelAk312** [comment]
Hi, I can try to help you with your error I just need to know the full error code

**Comment by kessanro** [comment]
that is the main part of the error

**Comment by JoeBanks13** [comment]
What version of discord.js are you running and please quote the WHOLE error

**Comment by kessanro** [comment]
the latest version

**Comment by ZelAk312** [comment]
you will need to change the discord.js version because this bot is in v8 and the latest is v10

**Comment by kessanro** [comment]
how

**Comment by ZelAk312** [comment]
`npm install hydrabolt/discord.js#indev-old` this will install the v8 version

**Comment by kessanro** [comment]
ok

**Comment by kessanro** [comment]
[ERROR] You appear to have installed discord.js from hydrabolt/discord.js#indev-
old.This has been moved to hydrabolt/discord.js#v8. Please update your reference
s accordingly.
module.js:474
    throw err;

**Comment by ZelAk312** [comment]
Oh they moved it so now it should be `npm install hydrabolt/discord.js#v8`

**Comment by kessanro** [comment]
throw er; // Unhandled 'error' event
      ^

Error: listen EACCES [PORT OF SERVER HERE]
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1249:19)
    at listen (net.js:1298:10)
    at Server.listen (net.js:1382:7)
    at Function.listen (C:\Users\User\Desktop\bot\node_modules\express
cation.js:617:24)
    at Object.<anonymous> (C:\Users\User\Desktop\bot\mb.js:49:13)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)

**Comment by kessanro** [comment]
errors Video not found please try to use a youtube video.

**Comment by kessanro** [comment]
cant find the youtube video
i put -play https://www.youtube.com/watch?v=GZrddJPGp1I
and not working
i placed - ad my prefix

**Comment by developerCodex** [comment]
Hmm.

**Comment by developerCodex** [comment]
What's the server invite link to your server, that your bot is currently running on? @kessanro
